name: Test

on:
  push:
    branches-ignore:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - run: bash .ci/runChecks.sh
  test-loki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm run test:ci:lokijs
  test-mongo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: supercharge/mongodb-github-action@1.6.0
      - run: npm run test:ci:mongodb
